name: docker hub release

# build master with multi-arch to docker hub

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
 
jobs:
  buildx-dockerhub:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: pinyinsearch/pinyin-search
      DOCKER_PLATFORMS: linux/amd64,linux/arm,linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: pinyinsearch/pinyin-search
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub # login to Docker Hub, automatically logout at the end of job
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run buildx and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # push to docker hub
          platforms: ${{ env.DOCKER_PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
